version: '3.8'

services:
  # --- Servicio de MongoDB (sin autenticación) ---
  mongo:
    image: mongo:latest
    container_name: tickets_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- Servicio de tu Aplicación Flask ---
  tickets_web:
    build: .
    container_name: tickets
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=1
      # La aplicación se conectará a esta URI, sin usuario/contraseña
      - MONGO_URI=mongodb://mongo:27017/ticketing_db
    depends_on:
      - mongo
    command: >
      bash -c "flask init-db-data && flask run --host=0.0.0.0 --port=5000 --reload --debugger"

# --- Definición de Volúmenes ---
volumes:
  mongo_data: