[tool.ruff]
# Ignora los errores F401 (importación no usada) y E402 (importación no al inicio del archivo)
# específicamente en los archivos __init__.py.
per-file-ignores = {"__init__.py" = ["F401", "E402"]}
