"""migracion inicial

Revision ID: e8bf824bdd96
Revises: 
Create Date: 2025-08-21 12:27:25.895749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bf824bdd96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('value')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('value')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('value')
    )
    op.create_table('personas',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('middleName', sa.String(length=100), nullable=True),
    sa.Column('firstSurname', sa.String(length=100), nullable=False),
    sa.Column('secondSurname', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.Column('completed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('asignated_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('asigned_operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignated_supervisor_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['asigned_operator_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('previous_category_id', sa.Integer(), nullable=True),
    sa.Column('new_category_id', sa.Integer(), nullable=True),
    sa.Column('previous_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=True),
    sa.Column('previous_description', sa.Text(), nullable=True),
    sa.Column('new_description', sa.Text(), nullable=True),
    sa.Column('previous_observation', sa.Text(), nullable=True),
    sa.Column('new_observation', sa.Text(), nullable=True),
    sa.Column('previous_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('new_supervisor_id', sa.Integer(), nullable=True),
    sa.Column('previous_operator_id', sa.Integer(), nullable=True),
    sa.Column('new_operator_id', sa.Integer(), nullable=True),
    sa.Column('change_timestamp', sa.DateTime(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=255), nullable=False),
    sa.Column('change_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['new_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['new_operator_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['new_status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['new_supervisor_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['previous_category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['previous_operator_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['previous_status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['previous_supervisor_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_history')
    op.drop_table('ticket')
    op.drop_table('personas')
    op.drop_table('status')
    op.drop_table('role')
    op.drop_table('category')
    # ### end Alembic commands ###
