name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }} # OBTENER DE GCP
  GCP_REGION: "us-central1" # OBTENER DE GCP
  CLOUD_RUN_SERVICE_NAME: "ticketing-app" # CAMBIAR
  ARTIFACT_REGISTRY_REPO: "ticketing-run-repo" # CAMBIAR

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     pytest

  # deploy:
  #   name: Deploy to Cloud Run
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: ${{ secrets.GCP_SA_KEY }}

  #     - name: Set up Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v2

  #     - name: Configure Docker
  #       run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}

  #     - name: Deploy to Cloud Run
  #       uses: google-github-actions/deploy-cloudrun@v2
  #       with:
  #         service: ${{ env.CLOUD_RUN_SERVICE_NAME }}
  #         region: ${{ env.GCP_REGION }}
  #         image: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.CLOUD_RUN_SERVICE_NAME }}:${{ github.sha }}
  #         platform: "managed"
  #         allow-unauthenticated: true # Cambiar a false si requieres autenticación
